= What are good alternatives to data fetching in Effects? 

Writing `fetch` calls inside Effects is a https://www.robinwieruch.de/react-hooks-fetch-data[popular way to fetch data], especially in fully client-side apps. This is, however, a very manual approach and it has significant downsides:

* *Effects don’t run on the server.* This means that the initial server-rendered HTML will only include a loading state with no data. The client computer will have to download all JavaScript and render your app only to discover that now it needs to load the data. This is not very efficient.

* *Fetching directly in Effects makes it easy to create “network waterfalls”.* You render the parent component, it fetches some data, renders the child components, and then they start fetching their data. If the network is not very fast, this is significantly slower than fetching all data in parallel.

* *Fetching directly in Effects usually means you don’t preload or cache data.* For example, if the component unmounts and then mounts again, it would have to fetch the data again.

* *It’s not very ergonomic.* There’s quite a bit of boilerplate code involved when writing `fetch` calls in a way that doesn’t suffer from bugs like https://maxrozen.com/race-conditions-fetching-data-react-with-useeffect[race conditions].

This list of downsides is not specific to React. It applies to fetching data on mount with any library. Like with routing, data fetching is not trivial to do well, so we recommend the following approaches:

* *If you use a https://react.dev/learn/start-a-new-react-project#production-grade-react-frameworks[framework], use its built-in data fetching mechanism.* Modern React frameworks have integrated data fetching mechanisms that are efficient and don’t suffer from the above pitfalls.

* *Otherwise, consider using or building a client-side cache.* Popular open source solutions include React Query, useSWR, and React Router 6.4+. You can build your own solution too, in which case you would use Effects under the hood, but add logic for deduplicating requests, caching responses, and avoiding network waterfalls (by preloading data or hoisting data requirements to routes).

You can continue fetching data directly in Effects if neither of these approaches suit you.