= JavaScript data types and data structures
:toc: right
:source-highlighter: highlight.js
:highlightjs-theme: xcode
:description: mdn上的，js基本数据类型和数据结构，阅读笔记，注意本文中的某些链接是链接到另一篇本地文章的，有些一些则链接到互联网。
lasting <lastingcoder@qq.com>

mdn上的，js基本数据类型和数据结构，阅读笔记，注意本文中的某些链接是链接到另一篇本地文章的，有些一些则链接到互联网。

== Dynamic and weak typing
====
[source,js]
.dynamic types
----
let foo = 42; // foo is now a number
foo = "bar"; // foo is now a string
foo = true; // foo is now a boolean
----

[source,js]
.weakly typed
----
const foo = 42; // foo is a number
const result = foo + "1"; // JavaScript coerces foo to a string, so it can be concatenated with the other operand
console.log(result); // 421
----
====

[NOTE]
====
For symbols and BigInts, JavaScript has intentionally disallowed certain implicit type conversions.
====

== Primitive values
|===
|Type|typeof returned value|Object wrapper

|Null
|"object"
|N/A

|Undefined
|"undefined"
|N/A

|Boolean
|"boolean"
|Boolean

|Number
|"number"
|Number

|BigInt
|"bigint"
|BigInt

|String
|"string"
|String

|Symbol
|"symbol"
|Symbol

|===

== Objects
=== Properties
* data property

* accessor property

* detaild see link:../Object.defineProperties/index.html[Object.defineProperty]

=== Dates
* When representing dates, the best choice is to use the built-in Date utility in JavaScript.

=== Indexed collections: Arrays and typed Arrays
* Arrays are regular objects for which there is a particular relationship between integer-keyed properties and the length property.

* Additionally, arrays inherit from Array.prototype, which provides a handful of convenient methods to manipulate arrays.

* link:[Typed Arrays] present an array-like view of an underlying binary data buffer, and offer many methods that have similar semantics to the array counterparts.Typed arrays are often used in conjunction with ArrayBuffer and DataView.

=== Keyed collections: Maps, Sets, WeakMaps, WeakSets
* These data structures take object references as keys. Set and WeakSet represent a collection of unique values, while Map and WeakMap represent a collection of key-value associations.

* Usually, to bind data to a DOM node, one could set properties directly on the object, or use data-* attributes. This has the downside that the data is available to any script running in the same context. Maps and WeakMaps make it easy to privately bind data to an object.

* WeakMap and WeakSet only allow object keys, and the keys are allowed to be garbage collected even when they remain in the collection. They are specifically used for memory usage optimization.

=== Structured data: JSON
* JSON (JavaScript Object Notation) is a lightweight data-interchange format, derived from JavaScript, but used by many programming languages. JSON builds universal data structures that can be transferred between different environments and even across languages. See JSON for more details.

=== More objects in the standard library
see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects[Standard built-in objects]

== Type coercion
=== Primitive coercion
for example:

* The Date() constructor, when it receives one argument that's not a Date instance — strings represent date strings, while numbers represent timestamps.

* The + operator — if one operand is a string, string concatenation is performed; otherwise, numeric addition is performed.

* The == operator — if one operand is a primitive while the other is an object, the object is converted to a primitive value with no preferred type.

This operation does not do any conversion if the value is already a primitive. Objects are converted to primitives by calling its [@@toPrimitive]() (with "default" as hint), valueOf(), and toString() methods, in that order. Note that primitive conversion calls valueOf() before toString(), which is similar to the behavior of number coercion but different from string coercion.

The [@@toPrimitive]() method, if present, must return a primitive — returning an object results in a TypeError. For valueOf() and toString(), if one returns an object, the return value is ignored and the other's return value is used instead; if neither is present, or neither returns a primitive, a TypeError is thrown. For example, in the following code:

====
[source,js]
----
console.log({} + []); // "[object Object]"
----
====

Neither {} nor [] has a [@@toPrimitive]() method. Both {} and [] inherit valueOf() from Object.prototype.valueOf, which returns the object itself. Since the return value is an object, it is ignored. Therefore, toString() is called instead. {}.toString() returns "[object Object]", while [].toString() returns "", so the result is their concatenation: "[object Object]".

The [@@toPrimitive]() method always takes precedence when doing conversion to any primitive type. Primitive conversion generally behaves like number conversion, because valueOf() is called in priority; however, objects with custom [@@toPrimitive]() methods can choose to return any primitive. Date and Symbol objects are the only built-in objects that override the [@@toPrimitive]() method. Date.prototype[@@toPrimitive]() treats the "default" hint as if it's "string", while Symbol.prototype[@@toPrimitive]() ignores the hint and always returns a symbol.

=== Numeric coercion
There are two numeric types: number and BigInt. Sometimes the language specifically expects a number or a BigInt (such as Array.prototype.slice(), where the index must be a number); other times, it may tolerate either and perform different operations depending on the operand's type. For strict coercion processes that do not allow implicit conversion from the other type, see number coercion and BigInt coercion.

Numeric coercion is nearly the same as number coercion, except that BigInts are returned as-is instead of causing a TypeError. Numeric coercion is used by all arithmetic operators, since they are overloaded for both numbers and BigInts. The only exception is unary plus, which always does number coercion.

=== Boolean coercion
* Boolean are returned as-is

* `undefined` turns into `false`

* `null` turns into `false`
 
* `0`,`-0`,`NaN` turns into `false`;other numbers turns into `true`

* `0n` turns into `false`;other BigInts turn into `true`

* `Symbols` turn into `true`

* All objects become `true`

[NOTE]
====
A legacy behavior makes document.all return false when used as a boolean, despite it being an object. This property is legacy and non-standard and should not be used.
====

[NOTE]
====
Unlike other type conversions like string coercion or number coercion, boolean coercion does not attempt to convert objects to primitives.
====

In other words, there are only a handful of values that get coerced to false — these are called link:res/falsy.adoc[falsy] values. All other values are called truthy values. A value's truthiness is important when used with logical operators, conditional statements, or any boolean context.

There are two ways to achieve the same effect in JavaScript.

* Double NOT: !!x negates x twice, which converts x to a boolean using the same algorithm as above.

* The Boolean() function: Boolean(x) uses the same algorithm as above to convert x.

[NOTE]
====
Note that truthiness is not the same as being loosely equal to true or false.
====

====
.example
```js
if ([]) {
  console.log("[] is truthy");
}
if ([] == false) {
  console.log("[] == false");
}
// [] is truthy
// [] == false
```
====

[] is truthy, but it's also loosely equal to false. It's truthy, because all objects are truthy. However, when comparing with false, which is a primitive, [] is also converted to a primitive, which is "" via Array.prototype.toString(). Comparing strings and booleans results in both being converted to numbers, and they both become 0, so [] == false is true. In general, falsiness and == false differ in the following cases:

* NaN, undefined, and null are falsy but not loosely equal to false.

* "0" (and other string literals that are not "" but get coerced to 0) is truthy but loosely equal to false.

* Objects are always truthy, but their primitive representation may be loosely equal to false.

Truthy values are even more unlikely to be loosely equal to true. All values are either truthy or falsy, but most values are loosely equal to neither true nor false.

=== String coercion
* String are returned as-is

* undefined turns into `'undefined'`

* null turns into `'null'`

* true turns into `'true'`,false turns into `'false'`

* Numbers are converted with the same algorithm as `toString(10)`

* BigInts are converted with the same algorithm as toString(10)

* Symbols throw a TypeError

* Objects are first converted to a primitive by calling its [@@toPrimitive]() (with "string" as hint), toString(), and valueOf() methods, in that order. The resulting primitive is then converted to a string.

There are several ways to achieve nearly the same effect in JavaScript.

* Template literal: `${x}` does exactly the string coercion steps explained above for the embedded expression.

* The String() function: String(x) uses the same algorithm to convert x, except that Symbols don't throw a TypeError, but return "Symbol(description)", where description is the description of the Symbol.

* Using the + operator: "" + x coerces its operand to a primitive instead of a string, and, for some objects, has entirely different behaviors from normal string coercion. See its reference page for more details.

Depending on your use case, you may want to use `${x}` (to mimic built-in behavior) or String(x) (to handle symbol values without throwing an error), but you should not use "" + x.

=== Object coercion
* Objects are return as-is

* undefined and null throw a TypeError.

* Number, String, Boolean, Symbol, BigInt primitives are wrapped into their corresponding object wrappers.

The best way to achieve the same effect in JavaScript is through the Object() constructor. Object(x) converts x to an object, and for undefined or null, it returns a plain object instead of throwing a TypeError.

Places that use object coercion include:

* The object parameter of for...in loops.
* The this value of Array methods.
* Parameters of Object methods such as Object.keys().
* Auto-boxing when a property is accessed on a primitive value, since primitives do not have properties.
* The this value when calling a non-strict function. Primitives are boxed while null and undefined are replaced with the global object.

Unlike conversion to primitives, the object coercion process itself is not observable in any way, since it doesn't invoke custom code like toString or valueOf methods.

=== Other coercions
All data types, except _Null_, _Undefined_, and _Symbol_, have their respective coercion process.

As you may have noticed, there are three distinct paths through which objects may be converted to primitives:

* Primitive coercion: `[@@toPrimitive]("default")` → `valueOf()` → `toString()`

* Numeric coercion, number coercion, BigInt coercion: `[@@toPrimitive]("number")` → `valueOf()` → `toString()`

* String coercion: `[@@toPrimitive]("string")` → `toString()` → `valueOf()`