= validation
:toc: right
:source-highlighter: highlight.js
:highlightjs-theme: a11y-light
:description: introduce validation pipe in graphQL
lasting <lastingcoder@qq.com>

== Using the built-in ValidationPipe

====
```bash
$ npm i --save class-validator class-transformer
```
====

== Auto-validation

====
```ts
async function bootstrap() {    
  const app = await NestFactory.create(AppModule);
  app.useGlobalPipes(new ValidationPipe());
  await app.listen(3000);
}
bootstrap();
```
====


=== class validator

====
```ts
import { IsEmail, IsNotEmpty } from 'class-validator';

export class CreateUserDto {
  @IsEmail()
  email: string;

  @IsNotEmpty()
  password: string;
}
```
====

== Disable detailed errors

====
[source,ts]
----
app.useGlobalPipes(
  new ValidationPipe({
    disableErrorMessages: true,
  }),
);
----
====

== Stripping properties

Our `ValidationPipe` can also filter out properties that should not be received by the method handler. In this case, we can whitelist the acceptable properties, and any property not included in the whitelist is automatically stripped from the resulting object. 

====
```ts
app.useGlobalPipes(
  new ValidationPipe({
    whitelist: true,
  }),
);
```
====

When set to true, this will automatically remove non-whitelisted properties (those without any decorator in the validation class).

Alternatively, you can stop the request from processing when non-whitelisted properties are present, and return an error response to the user. To enable this, set the *#forbidNonWhitelisted#* option property to *#true#*, in combination with setting *#whitelist#* to *#true#*.

== Transform payload objects

method level

====
```ts
@Post()
@UsePipes(new ValidationPipe({ transform: true }))
async create(@Body() createCatDto: CreateCatDto) {
  this.catsService.create(createCatDto);
}
```
====

or global level

====
```ts
app.useGlobalPipes(
  new ValidationPipe({
    transform: true,
  }),
);
```
====

With the auto-transformation option enabled, the *#ValidationPipe#* will also perform conversion of primitive types. In the following example, the *#findOne#*() method takes one argument which represents an extracted *#id#* path parameter:

====
```ts
@Get(':id')
findOne(@Param('id') id: number) {
  console.log(typeof id === 'number'); // true
  return 'This action returns a user';
}
```
====

By default, every path parameter and query parameter comes over the network as a *#string#*. In the above example, we specified the *#id#* type as a *#number#* (in the method signature). Therefore, the *#ValidationPipe#* will try to automatically convert a string identifier to a number.

== Explicit conversion

====
```ts
@Get(':id')
findOne(
  @Param('id', ParseIntPipe) id: number,
  @Query('sort', ParseBoolPipe) sort: boolean,
) {
  console.log(typeof id === 'number'); // true
  console.log(typeof sort === 'boolean'); // true
  return 'This action returns a user';
}
```
====

== Mapped types

you have an entity class

====
```ts
export class CreateCatDto {
  name: string;
  age: number;
  breed: string;
}
```
====

=== PartialType

By default, all of these fields are required. To create a type with the same fields, but with each one optional, use *#PartialType()#* passing the class reference (*#CreateCatDto#*) as an argument:

====
```ts
export class UpdateCatDto extends PartialType(CreateCatDto) {}
```
====

=== PickType

We can pick a set of properties from this class using the *#PickType()#* utility function:

====
```ts
export class UpdateCatAgeDto extends PickType(CreateCatDto, ['age'] as const) {}
```
====

=== OmitType

We can generate a derived type that has every property exceptname as shown below. In this construct, the second argument to *#OmitType#* is an array of property names.

====
```ts
export class UpdateCatDto extends OmitType(CreateCatDto, ['name'] as const) {}
```
====

=== IntersectionType

====
```ts
export class CreateCatDto {
  name: string;
  breed: string;
}

export class AdditionalCatInfo {
  color: string;
}
```
====

We can generate a new type that combines all properties in both types.

====
```ts
export class UpdateCatDto extends IntersectionType(
  CreateCatDto,
  AdditionalCatInfo,
) {}
```
====

The type mapping utility functions are composable. For example, the following will produce a type (class) that has all of the properties of the *#CreateCatDto#* type except for *#name#*, and those properties will be set to optional:

====
```ts
export class UpdateCatDto extends PartialType(
  OmitType(CreateCatDto, ['name'] as const),
) {}
```
====

=== Parsing and validating arrays

TypeScript does not store metadata about generics or interfaces, so when you use them in your DTOs, *#ValidationPipe#* may not be able to properly validate incoming data. For instance, in the following code, *#createUserDtos#* won't be correctly validated:

====
```ts
@Post()
createBulk(@Body() createUserDtos: CreateUserDto[]) {
  return 'This action adds new users';
}
```
====

To validate the array, create a dedicated class which contains a property that wraps the array, or use the *#ParseArrayPipe#*.

====
```ts
@Post()
createBulk(
  @Body(new ParseArrayPipe({ items: CreateUserDto }))
  createUserDtos: CreateUserDto[],
) {
  return 'This action adds new users';
}
```
====

or you can use it handy query parameters

====
```ts
@Get()
findByIds(
  @Query('ids', new ParseArrayPipe({ items: Number, separator: ',' }))
  ids: number[],
) {
  return 'This action returns users by ids';
}
```
====

This construction validates the incoming query parameters from an HTTP GET request like the following:

====
GET /?ids=1,2,3
====

== WebSockets and Microservices

While this chapter shows examples using HTTP style applications (e.g., Express or Fastify), the *#ValidationPipe#* works the same for WebSockets and microservices, regardless of the transport method that is used.