= Authorizing OAuth apps
:toc: right

You can enable other users to authorize your OAuth app.

To authorize your OAuth app, consider which authorization flow best fits your app.

* web application flow: Used to authorize users for standard OAuth apps that run in the browser. (The implicit grant type is not supported.)
* device flow: Used for headless apps, such as CLI tools.

== Web application flow
The web application flow to authorize users for your app is:

. Users are redirected to request their GitHub identity
. Users are redirected back to your site by GitHub
. Your app accesses the API with the user's access token

=== 1. Request a user's GitHub identity
----
GET https://github.com/login/oauth/authorize
----
This endpoint takes the following input parameters.

[cols="1m,1m,3a"]
|===
|Parameter name|Type|Description

|client_id
|string	
|*Required*. The client ID you received  from GitHub when you registered.

|redirect_uri
|string
|The URL in your application where users will be sent after authorization. See details below about redirect urls.

|login	
|string	
|Suggests a specific account to use for signing in and authorizing the app.

|scope	
|string	
|A space-delimited list of scopes. If not provided, scope defaults to an empty list for users that have not authorized any scopes for the application. For users who have authorized scopes for the application, the user won't be shown the OAuth authorization page with the list of scopes. Instead, this step of the flow will automatically complete with the set of scopes the user has authorized for the application. For example, if a user has already performed the web flow twice and has authorized one token with user scope and another token with repo scope, a third web flow that does not provide a scope will receive a token with user and repo scope.

|state	
|string	
|An unguessable random string. It is used to protect against cross-site request forgery attacks.

|allow_signup	
|string	
|Whether or not unauthenticated users will be offered an option to sign up for GitHub during the OAuth flow. The default is true. Use false when a policy prohibits signups.
|===

=== 2. Users are redirected back to your site by GitHub

If the user accepts your request, GitHub redirects back to your site with a temporary code in a code parameter as well as the state you provided in the previous step in a state parameter. The temporary code will expire after 10 minutes. If the states don't match, then a third party created the request, and you should abort the process.

Exchange this code for an access token:
----
POST https://github.com/login/oauth/access_token
----

This endpoint takes the following input parameters.

[cols="1m,1m,3a"]
|===
|Parameter name	|Type	|Description

|client_id	
|string	
|*Required*. The client ID you received from GitHub for your OAuth app.

|client_secret	
|string	
|*Required*. The client secret you received from GitHub for your OAuth app.

|code	
|string	
|*Required*. The code you received as a response to Step 1.

|redirect_uri	
|string	
|The URL in your application where users are sent after authorization.
|===

By default, the response takes the following form:
----
access_token=gho_16C7e42F292c6912E7710c838347Ae178B4a&scope=repo%2Cgist&token_type=bearer
----

You can also receive the response in different formats if you provide the format in the Accept header. For example, Accept: application/json or Accept: application/xml:

----
Accept: application/json
{
  "access_token":"gho_16C7e42F292c6912E7710c838347Ae178B4a",
  "scope":"repo,gist",
  "token_type":"bearer"
}
----

----
Accept: application/xml
<OAuth>
  <token_type>bearer</token_type>
  <scope>repo,gist</scope>
  <access_token>gho_16C7e42F292c6912E7710c838347Ae178B4a</access_token>
</OAuth>
----

=== 3. Use the access token to access the API
The access token allows you to make requests to the API on a behalf of a user.

----
Authorization: Bearer OAUTH-TOKEN
GET https://api.github.com/user
----
For example, in curl you can set the Authorization header like this:

----
curl -H "Authorization: Bearer OAUTH-TOKEN" https://api.github.com/user
----
